#!/usr/bin/env bash
# Bootstrap script for installing dotfiles and dependencies.
# Usage: Run this script from the dotfiles repository root.
#        ./bootstrap

set -eu # Exit on error or unset variable

# Helper functions for logging.
info() {
  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
}

user() {
  printf "\r  [ \033[0;33m??\033[0m ] $1\n"
}

success() {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail() {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

# Install Homebrew

if ! command -v brew &>/dev/null; then
  info "   Installing Homebrew"
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
else
  info "   Homebrew already installed"
fi

# Ensure brew env is added to .zprofile
if ! grep -q "brew shellenv" ~/.zprofile; then
  echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >>~/.zprofile
  info "   Added Homebrew shellenv to .zprofile"
fi

# Install ohmyzsh
if [[ ! -d "$HOME/.oh-my-zsh" ]]; then
  echo "   Installing oh-my-zsh"
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

# Install mise
if ! command -v mise &>/dev/null; then
  info "Installing mise"
  brew install mise
else
  info "   Mise already installed"
fi

# Mise bootstrap
mise trust
mise bootstrap --yes
