# oh-my-zsh stuff

# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time Oh My Zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
# ZSH_THEME="robbyrussell"

# Using starship for prompt.
ZSH_THEME=""

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(mise)

source $ZSH/oh-my-zsh.sh

source "$HOME/.config/shell/zoptions.zsh"
source "$HOME/.config/shell/envs.sh"
source "$HOME/.config/shell/aliases.sh"
source "$HOME/.config/shell/functions.sh"

# Stash your environment variables in ~/.localrc. This means they'll stay out
# of your main dotfiles repository (which may be public, like this one), but
# you'll have access to them in your scripts.
if [[ -a ~/.localrc ]]
then
  source ~/.localrc
fi

# Initialize autocomplete here, otherwise functions won't be loaded
autoload -U compinit
compinit

source "$HOME/.config/shell/inits.sh"
