name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Shellcheck bin scripts
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: "./bin"
          severity: warning

      - name: Shellcheck scripts
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: "./script"
          severity: warning
